steps:
    - key: echo
    command:
    - echo $TEST_CONDITION
    - key: test-if-str
    if: build.env("TEST_CONDITION") == "true"
    command:
    - echo "string"
    - key: test-if-str-single-quotes
    if: build.env("TEST_CONDITION") == 'true'
    command:
    - echo "string single quotes"
    - key: test-if-regex
    if: build.env("TEST_CONDITION") =~ /true/
    command:
    - echo "regex"
