steps:
    - label: "echo"
      command:
      - "echo true"
    - if: "build.env(\"TEST_CONDITION\") == \"true\""
      label: "test-if-str"
      command:
      - "echo \"string\""
    - if: "build.env(\"TEST_CONDITION\") == 'true'"
      label: "test-if-str-single-quotes"
      command:
      - "echo \"string single quotes\""
    - if: "build.env(\"TEST_CONDITION\") =~ /true/"
      label: "test-if-regex"
      command:
      - "echo \"regex\""